source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ABOnboarding_Example', :exclusive => true do
  pod 'ABOnboarding', :path => '../'
end

target 'ABOnboarding_Tests', :exclusive => true do
  pod 'ABOnboarding', :path => '../'

  
end
